### ISSUE TITLE
Can I use it with "svelte" in addition to just the "svelte kit"?

### ISSUE THREAD

**Issue by nadolny** [shinokada/flowbite-svelte-blocks#3]
Hello Shinokada.
Great Work. 

The question is addressed to the following scope:

If you want to get started with Svelte:
With the following Installing from scratch:

npm create vite@latest myapp -- --template svelte
cd myapp
npm install

...

I ask because I see great possibilities with pure svelte too.
My interest is more focused on svelte to use with other backends.

Thanks.

**Comment by shinokada** [comment]
Yes, it should work.
I have used Flowbite-Svelte for Svelte as well.
