### ISSUE TITLE
[BUG]: Package name when installed is `my-app1`

### ISSUE THREAD

**Issue by t-miller** [shinokada/flowbite-svelte-blocks#6]
### Description of the bug

When I run `pnpm i -D shinokada/flowbite-svelte-blocks` my `package.json` adds `"my-app1": "github:shinokada/flowbite-svelte-blocks"` in devDependencies and is under `my-app1` in `node_modules`

### Steps To Reproduce

1. Run `pnpm i -D shinokada/flowbite-svelte-blocks`

**Comment by shinokada** [comment]
Thanks. I will fix it asap.

**Comment by shinokada** [comment]
I've updated the package to support the latest versions of Svelte and SvelteKit, and I've also made some changes to the packaging. Could you please give it a try and let me know if everything looks good on your end? Thanks!
