### ISSUE TITLE
[BUG]: TypeScript Intellisense broken after latest upgrade

### ISSUE THREAD

**Issue by Destaq** [shinokada/flowbite-svelte-blocks#8]
### Description of the bug

After moving from version 0.2.X to 0.3.X of the library, there is no longer support for `flowbite-svelte-block`'s types in the code editor.

I believe that this is due to some of the 'BREAKING CHANGE[s]' introduced, but since there is no new documentation, I'm not sure how to fix this.

I've been able to get type information by changing `import { XXX } from "flowbite-svelte-blocks"` to `import { XX } from "flowbite-svelte-blocks/dist"`. However, when then running the application with this new import style, a 500 server error pops up and pages can't be opened.

<img width="449" alt="image" src="https://user-images.githubusercontent.com/61620873/220209242-f43a821d-74ce-4556-aa58-797cbd0bd3ee.png">

### Steps To Reproduce

1. Go to https://flowbite-svelte-blocks.vercel.app/marketing/pricing
2. Click on 'Edit on GitHub'
3. Copy the raw code into a new Svelte project folder (after setting up `flowbite`, `flowbite-svelte`, etc.)
4. Notice that there is a squiggly red line and no information about types

### Additional Information

<img width="506" alt="image" src="https://user-images.githubusercontent.com/61620873/220208729-f9eaf359-2ece-42de-9707-41eb0d303d84.png">
<img width="166" alt="image" src="https://user-images.githubusercontent.com/61620873/220209026-5af9753f-3e76-4ed1-95cf-e9bb9de5cb43.png">

**Comment by shinokada** [comment]
I already fixed it. Please update to the latest version.

**Comment by Destaq** [comment]
Ah, I needed to explicitly set the versions of `flowbite-svelte` and `flowbite-svelte-blocks` in my `package.json` to their latest versions. Thank you for the help.
