### ISSUE TITLE
[BUG]: Could not resolve "./QrCode.svelte" from "node_modules/svelte-heros/dist/index.js"

### ISSUE THREAD

**Issue by neospirit** [shinokada/flowbite-svelte-blocks#9]
### Description of the bug

When building on CI (Github actions) there is a build error saying:
`Could not resolve "./QrCode.svelte" from "node_modules/svelte-heros/dist/index.js"`

It seems that the file in svelte-heros is `Qrcode.svelte` and not `QrCode.svelte`

### Steps To Reproduce

Not really a step to reproduce here apart making a project and building into production.

**Comment by neospirit** [comment]
Sorry wrong repo. It was meant for https://github.com/shinokada/svelte-heros => https://github.com/shinokada/svelte-heros/issues/7

**Comment by shinokada** [comment]
I updated svelte-heros@2.9.1.
